network_name: 
  - nature_cnn
trainer_name: 
  - adam
epsilon: 
  - 0.9 #probability to play a random action
epsilon_decay: 
  - 125000 # number of backprop cycles to linear scale epsilon to 1. Put 0 for no decay
frame_stacks: 
  - 3
  - 1
max_epochs: 
  - 750
max_length_dataset: 
  - 10000000 # Maximum size of the replay network dataset
learning_rate: 
  - 0.00025 
replay_start_size: 
  - 50 # Number of states of random play, before network starts action picking  
mini_batch_size: 
  - 16
network_copy: 
  - 1000 # Number of backprop cycles needed to copy network weigths from training to target network
epoch_length: 
  - 2500
gui: # Play via pygame (gui) or numpy backend (no gui but faster)
  - True
